name: Build and Push to Docker Hub

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/phonestore-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/phonestore-api:${{ github.sha }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./aa2-frontend
          file: aa2-frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/phonestore-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/phonestore-frontend:${{ github.sha }}
